- hosts: localhost
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Update APT
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - include: tasks/core_setup.yml
    - include: tasks/brave.yml
    - include: tasks/spotify.yml
    - include: tasks/vscode.yml
    - include: tasks/windscribe.yml
    - include: tasks/miniconda.yml
    - include: tasks/r.yml
    - include: tasks/desktop.yml
    - include: tasks/dotfiles.yml