- hosts: localhost
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Update APT
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - include_tasks: tasks/core_setup.yml
    - include_tasks: tasks/miniconda.yml
    - include_tasks: tasks/r.yml
    - include_tasks: tasks/desktop.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/deb_get.yml
