- name: Installing wget & unzip
  become: true
  apt:
    name: ["wget", "unzip"]

- name: Create apps Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/apps"
    state: directory

- name: Download pCloud AppImage Zip
  shell:
    cmd: |
      cd $HOME/apps && \
      curl -s https://www.pcloud.com/how-to-install-pcloud-drive-linux.html?download=electron-64 \
      | grep "'Electron':" \
      | cut -d : -f 2,3 \
      | tr -d \" \
      | sed "s/[,']//g" \
      | sed "s/[[:blank:]]//g" \
      | xargs echo "https://api.pcloud.com/getpubzip?code=" \
      | sed "s/[[:blank:]]//g" \
      | wget -O pcloud.zip -qi -

- name: Extract pCloud AppImage Zip
  shell:
    cmd: |
      cd $HOME/apps && unzip pcloud.zip && rm pcloud.zip && chmod +x pcloud && mv pcloud pcloud.AppImage

- name: Download Bitwarden CLI
  shell:
    cmd: |
      cd $HOME/apps && \
      curl -s https://api.github.com/repos/bitwarden/cli/releases/latest \
      | grep "bw-linux*.*zip" \
      | cut -d : -f 2,3 \
      | tr -d \" \
      | wget -O bw.zip -qi -

- name: Extract Bitwarden CLI
  shell:
    cmd: |
      cd $HOME/apps && unzip bw.zip && rm bw.zip && chmod +x bw
