- name: Clone deb-get repository
  become: true
  git:
    repo: "https://github.com/wimpysworld/deb-get.git"
    dest: "/tmp/deb-get"
    clone: yes
    force: yes

- name: Reset repository (hard reset)
  become: true
  command:
    cmd: git reset --hard
    chdir: /tmp/deb-get/

- name: Pull latest changes
  become: true
  git:
    repo: "https://github.com/wimpysworld/deb-get.git"
    dest: "/tmp/deb-get"
    update: yes

- name: Run make install
  become: true
  make:
    chdir: /tmp/deb-get/docs/
    target: install

- name: Update deb-get
  become: false
  shell: deb-get update 2>/dev/null || true

- name: Install Software
  become: true
  shell: sudo deb-get install standard-notes bitwarden whatsapp-for-linux spotify-client brave-browser code rstudio veracrypt indicator-sound-switcher mullvad-vpn 2>/dev/null || true
