- name: Ranger Desktop Entry
  become: true
  shell:
    cmd: |
      cat > /usr/share/applications/ranger.desktop <<EOL
      [Desktop Entry]
      Type=Application
      Name=ranger
      Comment=Launches the ranger file manager
      Icon=utilities-terminal
      Terminal=false
      Exec=urxvt -e ranger
      Categories=ConsoleOnly;System;FileTools;FileManager
      MimeType=inode/directory;
      Keywords=File;Manager;Browser;Explorer;Vi;Vim;Python
      EOL

- name: Ranger Inode
  shell: xdg-mime default ranger.desktop inode/directory

- name: RStudio Desktop Entry
  become: true
  shell:
    cmd: |
      cat > /usr/share/applications/rstudio.desktop <<EOL
      [Desktop Entry]
      Exec=env XDG_CURRENT_DESKTOP=GNOME /usr/lib/rstudio/bin/rstudio %F
      Icon=rstudio
      Type=Application
      Terminal=false
      Name=RStudio
      Categories=Development;IDE;
      MimeType=text/x-r-source;text/x-r;text/x-R;text/x-r-doc;text/x-r-sweave;text/x-r-markdown;text/x-r-html;text/x-r-presentation;application/x-r-data;application/x-r-project;text/x-r-history;text/x-r-profile;text/x-tex;text/x-markdown;text/html;text/css;text/javascript;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;
      EOL
