- name: Download Miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/install_miniconda.sh

- name: Install Miniconda
  shell: /tmp/install_miniconda.sh -b -p ~/.miniconda3

- name: Remove Miniconda Installer
  file:
    state: absent
    path: /tmp/install_miniconda.sh
