- name: R APT Key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: R Repository
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu {{lsb_release -cs}}-cran40/

- name: R APT Installation
  become: true
  apt:
    update_cache: yes
    name:
      [
        "r-base",
        "libssl-dev",
        "libcurl4-openssl-dev",
        "libxml2-dev",
        "libgmp3-dev",
        "libmpfr-dev",
        "libglpk-dev",
        "libnode-dev",
      ]

- name: R Replace Home Directory
  become: true
  shell: sed -i 's/\~\/R/\~\/\.R/g' /etc/R/Renviron

- name: R Change Package Repo
  become: true
  shell: sed -i 's/https:\/\/cloud\.r-project\.org/https:\/\/packagemanager\.rstudio\.com\/all\/__linux__\/focal\/latest/g' /etc/R/Rprofile.site

- name: R Create Personal Library
  shell:
    cmd: |
      R --vanilla << EOF
      dir.create(path = Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE)
      q()
      EOF

- name: Check RStudio Latest Version
  uri: url=http://download1.rstudio.org/current.ver  return_content=yes
  register: rstudio_version

- name: Download RStudio DEB
  get_url: url=https://download1.rstudio.org/desktop/bionic/amd64/rstudio-{{ rstudio_version.content }}-amd64.deb dest=/tmp/rstudio.deb

- name: Install RStudio DEB Package
  become: true
  apt:
    deb: /tmp/rstudio.deb

- name: Remove RStudio DEB Package
  file:
    state: absent
    path: /tmp/rstudio.deb
