- name: Install Rust and Cargo
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Ensure Cargo is in PATH for current session
  shell: . ~/.cargo/env
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Install yazi-fm and yazi-cli
  shell: cargo install --locked yazi-fm yazi-cli
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Install fd-find
  shell: cargo install fd-find
  become: true
  environment:
    HOME: "{{ ansible_env.HOME }}"
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
