name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "lazyvim/**"
      - "mac_scripts/**"
  workflow_dispatch:
env:
  VAULT_PASS: "${{ secrets.VAULT_PASS }}"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Build & Test Dotfiles
        run: |
          docker build --build-arg VAULT_PASS=$VAULT_PASS -t ansible-build -f Dockerfile .
          docker run ansible-build
